import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mr-36 ml-36">
          <div className="text-2xl text-center">
            <Link href="/">Home </Link>
            {/* <Link href="/snippets">Snippets </Link> */}
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
